import assert from 'node:assert/strict';
import { reportPayload } from '../src/components/reportPayload.js';
const base = { recordId: 'example', categories: ['incorrect_fact'], content: '', quotes: [], answer: '🙂 근정전. 근정전.', mode: 'v2' };
const first = { text: '근정전.', start_offset: 2, end_offset: 6 };
const second = { text: '근정전.', start_offset: 7, end_offset: 11 };
assert.deepEqual(reportPayload({ ...base, quotes: [first, second] }).selected_quotes, [first, second]);
assert.throws(() => reportPayload(base));
assert.throws(() => reportPayload({ ...base, categories: ['other'], quotes: [first] }));
assert.throws(() => reportPayload({ ...base, quotes: [{ ...first, start_offset: 3 }] }));
assert.throws(() => reportPayload({ ...base, quotes: [{ ...second, end_offset: 999 }] }));
assert.throws(() => reportPayload({ ...base, quotes: Array(6).fill(first) }));
assert.throws(() => reportPayload({ ...base, categories: [] }));
assert.throws(() => reportPayload({ ...base, content: '가'.repeat(2001) }));
const legacy = reportPayload({ ...base, mode: 'legacy', content: '가'.repeat(10) });
assert.equal(legacy.category, 'incorrect_fact');
assert.equal('selected_quotes' in legacy, false);
assert.equal('categories' in legacy, false);
assert.throws(() => reportPayload({ ...base, mode: 'legacy', content: '짧음' }));
assert.throws(() => reportPayload({ ...base, mode: 'legacy', categories: ['incorrect_fact', 'other'], content: '가'.repeat(10) }));
console.log('PASS: legacy fields, required explanation, other, empty category, quote count, exact offsets, Unicode/repeated phrases, length limit');
